[2023-10-19 04:44:00 +0000] [407133] [INFO] Starting gunicorn 21.2.0
[2023-10-19 04:44:00 +0000] [407133] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:44:00 +0000] [407133] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:01 +0000] [407133] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:44:01 +0000] [407133] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:02 +0000] [407133] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:44:02 +0000] [407133] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:03 +0000] [407133] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:44:03 +0000] [407133] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:04 +0000] [407133] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:44:04 +0000] [407133] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:05 +0000] [407133] [ERROR] Can't connect to ('0.0.0.0', 9000)
[2023-10-19 04:44:06 +0000] [407170] [INFO] Starting gunicorn 21.2.0
[2023-10-19 04:44:06 +0000] [407170] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:44:06 +0000] [407170] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:07 +0000] [407170] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:44:07 +0000] [407170] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:08 +0000] [407170] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:44:08 +0000] [407170] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:09 +0000] [407170] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:44:09 +0000] [407170] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:10 +0000] [407170] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:44:10 +0000] [407170] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:11 +0000] [407170] [ERROR] Can't connect to ('0.0.0.0', 9000)
[2023-10-19 04:44:32 +0000] [407257] [INFO] Starting gunicorn 21.2.0
[2023-10-19 04:44:32 +0000] [407257] [ERROR] Connection in use: ('0.0.0.0', 9001)
[2023-10-19 04:44:32 +0000] [407257] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:33 +0000] [407257] [ERROR] Connection in use: ('0.0.0.0', 9001)
[2023-10-19 04:44:33 +0000] [407257] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:34 +0000] [407257] [ERROR] Connection in use: ('0.0.0.0', 9001)
[2023-10-19 04:44:34 +0000] [407257] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:35 +0000] [407257] [ERROR] Connection in use: ('0.0.0.0', 9001)
[2023-10-19 04:44:35 +0000] [407257] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:36 +0000] [407257] [ERROR] Connection in use: ('0.0.0.0', 9001)
[2023-10-19 04:44:36 +0000] [407257] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:37 +0000] [407257] [ERROR] Can't connect to ('0.0.0.0', 9001)
[2023-10-19 04:44:38 +0000] [407294] [INFO] Starting gunicorn 21.2.0
[2023-10-19 04:44:38 +0000] [407294] [ERROR] Connection in use: ('0.0.0.0', 9001)
[2023-10-19 04:44:38 +0000] [407294] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:39 +0000] [407294] [ERROR] Connection in use: ('0.0.0.0', 9001)
[2023-10-19 04:44:39 +0000] [407294] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:40 +0000] [407294] [ERROR] Connection in use: ('0.0.0.0', 9001)
[2023-10-19 04:44:40 +0000] [407294] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:41 +0000] [407294] [ERROR] Connection in use: ('0.0.0.0', 9001)
[2023-10-19 04:44:41 +0000] [407294] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:42 +0000] [407294] [ERROR] Connection in use: ('0.0.0.0', 9001)
[2023-10-19 04:44:42 +0000] [407294] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:43 +0000] [407294] [ERROR] Can't connect to ('0.0.0.0', 9001)
[2023-10-19 04:44:44 +0000] [407303] [INFO] Starting gunicorn 21.2.0
[2023-10-19 04:44:44 +0000] [407303] [ERROR] Connection in use: ('0.0.0.0', 9001)
[2023-10-19 04:44:44 +0000] [407303] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:45 +0000] [407303] [ERROR] Connection in use: ('0.0.0.0', 9001)
[2023-10-19 04:44:45 +0000] [407303] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:46 +0000] [407303] [ERROR] Connection in use: ('0.0.0.0', 9001)
[2023-10-19 04:44:46 +0000] [407303] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:47 +0000] [407303] [ERROR] Connection in use: ('0.0.0.0', 9001)
[2023-10-19 04:44:47 +0000] [407303] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:48 +0000] [407303] [ERROR] Connection in use: ('0.0.0.0', 9001)
[2023-10-19 04:44:48 +0000] [407303] [ERROR] Retrying in 1 second.
[2023-10-19 04:44:49 +0000] [407303] [ERROR] Can't connect to ('0.0.0.0', 9001)
[2023-10-19 04:45:28 +0000] [407449] [INFO] Starting gunicorn 21.2.0
[2023-10-19 04:45:28 +0000] [407449] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:28 +0000] [407449] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:29 +0000] [407449] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:29 +0000] [407449] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:30 +0000] [407449] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:30 +0000] [407449] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:31 +0000] [407449] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:31 +0000] [407449] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:32 +0000] [407449] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:32 +0000] [407449] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:33 +0000] [407449] [ERROR] Can't connect to ('0.0.0.0', 9000)
[2023-10-19 04:45:34 +0000] [407515] [INFO] Starting gunicorn 21.2.0
[2023-10-19 04:45:34 +0000] [407515] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:34 +0000] [407515] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:35 +0000] [407515] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:35 +0000] [407515] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:36 +0000] [407515] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:36 +0000] [407515] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:37 +0000] [407515] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:37 +0000] [407515] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:38 +0000] [407515] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:38 +0000] [407515] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:39 +0000] [407515] [ERROR] Can't connect to ('0.0.0.0', 9000)
[2023-10-19 04:45:40 +0000] [407579] [INFO] Starting gunicorn 21.2.0
[2023-10-19 04:45:40 +0000] [407579] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:40 +0000] [407579] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:41 +0000] [407579] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:41 +0000] [407579] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:42 +0000] [407579] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:42 +0000] [407579] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:43 +0000] [407579] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:43 +0000] [407579] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:44 +0000] [407579] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:44 +0000] [407579] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:45 +0000] [407579] [ERROR] Can't connect to ('0.0.0.0', 9000)
[2023-10-19 04:45:46 +0000] [407589] [INFO] Starting gunicorn 21.2.0
[2023-10-19 04:45:46 +0000] [407589] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:46 +0000] [407589] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:47 +0000] [407589] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:47 +0000] [407589] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:48 +0000] [407589] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:48 +0000] [407589] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:49 +0000] [407589] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:49 +0000] [407589] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:50 +0000] [407589] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:50 +0000] [407589] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:51 +0000] [407589] [ERROR] Can't connect to ('0.0.0.0', 9000)
[2023-10-19 04:45:53 +0000] [407608] [INFO] Starting gunicorn 21.2.0
[2023-10-19 04:45:53 +0000] [407608] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:53 +0000] [407608] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:54 +0000] [407608] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:54 +0000] [407608] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:55 +0000] [407608] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:55 +0000] [407608] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:56 +0000] [407608] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:56 +0000] [407608] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:57 +0000] [407608] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:57 +0000] [407608] [ERROR] Retrying in 1 second.
[2023-10-19 04:45:58 +0000] [407608] [ERROR] Can't connect to ('0.0.0.0', 9000)
[2023-10-19 04:45:59 +0000] [407614] [INFO] Starting gunicorn 21.2.0
[2023-10-19 04:45:59 +0000] [407614] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:45:59 +0000] [407614] [ERROR] Retrying in 1 second.
[2023-10-19 04:46:00 +0000] [407614] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:46:00 +0000] [407614] [ERROR] Retrying in 1 second.
[2023-10-19 04:46:01 +0000] [407614] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:46:01 +0000] [407614] [ERROR] Retrying in 1 second.
[2023-10-19 04:46:02 +0000] [407614] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:46:02 +0000] [407614] [ERROR] Retrying in 1 second.
[2023-10-19 04:46:03 +0000] [407614] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:46:03 +0000] [407614] [ERROR] Retrying in 1 second.
[2023-10-19 04:46:04 +0000] [407614] [ERROR] Can't connect to ('0.0.0.0', 9000)
[2023-10-19 04:46:05 +0000] [407620] [INFO] Starting gunicorn 21.2.0
[2023-10-19 04:46:05 +0000] [407620] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:46:05 +0000] [407620] [ERROR] Retrying in 1 second.
[2023-10-19 04:46:06 +0000] [407620] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:46:06 +0000] [407620] [ERROR] Retrying in 1 second.
[2023-10-19 04:46:07 +0000] [407620] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:46:07 +0000] [407620] [ERROR] Retrying in 1 second.
[2023-10-19 04:46:08 +0000] [407620] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:46:08 +0000] [407620] [ERROR] Retrying in 1 second.
[2023-10-19 04:46:09 +0000] [407620] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:46:09 +0000] [407620] [ERROR] Retrying in 1 second.
[2023-10-19 04:46:10 +0000] [407620] [ERROR] Can't connect to ('0.0.0.0', 9000)
[2023-10-19 04:46:15 +0000] [407696] [INFO] Starting gunicorn 21.2.0
[2023-10-19 04:46:15 +0000] [407696] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:46:15 +0000] [407696] [ERROR] Retrying in 1 second.
[2023-10-19 04:46:16 +0000] [407696] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:46:16 +0000] [407696] [ERROR] Retrying in 1 second.
[2023-10-19 04:46:17 +0000] [407696] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:46:17 +0000] [407696] [ERROR] Retrying in 1 second.
[2023-10-19 04:46:18 +0000] [407696] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:46:18 +0000] [407696] [ERROR] Retrying in 1 second.
[2023-10-19 04:46:19 +0000] [407696] [ERROR] Connection in use: ('0.0.0.0', 9000)
[2023-10-19 04:46:19 +0000] [407696] [ERROR] Retrying in 1 second.
[2023-10-19 04:46:20 +0000] [407696] [ERROR] Can't connect to ('0.0.0.0', 9000)
[2023-10-19 04:47:43 +0000] [407971] [INFO] Starting gunicorn 21.2.0
[2023-10-19 04:47:43 +0000] [407971] [INFO] Listening at: http://0.0.0.0:9000 (407971)
[2023-10-19 04:47:43 +0000] [407971] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-10-19 04:47:43 +0000] [407974] [INFO] Booting worker with pid: 407974
[2023-10-19 04:47:43 +0000] [407975] [INFO] Booting worker with pid: 407975
2023-10-19 04:47:59.352156: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-19 04:47:59.352169: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-19 04:48:00.991278: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-10-19 04:48:00.991284: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-10-19 04:48:03.180884: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-19 04:48:03.180884: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-19 04:48:03.188176: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-10-19 04:48:03.188489: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
[2023-10-19 04:48:05 +0000] [407974] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/intent_generation/app.py", line 31, in <module>
    from Utils.get_intent_bert_basedANN import get_intent_one_by_one
  File "/home/ubuntu/intent_generation/Utils/get_intent_bert_basedANN.py", line 7, in <module>
    from utils.client import generate_seo_metatitle
ModuleNotFoundError: No module named 'utils'
[2023-10-19 04:48:05 +0000] [407974] [INFO] Worker exiting (pid: 407974)
[2023-10-19 04:48:05 +0000] [407975] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/intent_generation/app.py", line 31, in <module>
    from Utils.get_intent_bert_basedANN import get_intent_one_by_one
  File "/home/ubuntu/intent_generation/Utils/get_intent_bert_basedANN.py", line 7, in <module>
    from utils.client import generate_seo_metatitle
ModuleNotFoundError: No module named 'utils'
[2023-10-19 04:48:05 +0000] [407975] [INFO] Worker exiting (pid: 407975)
[2023-10-19 04:48:07 +0000] [407971] [ERROR] Worker (pid:407974) exited with code 3
[2023-10-19 04:48:07 +0000] [407971] [ERROR] Worker (pid:407975) exited with code 3
Traceback (most recent call last):
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 360, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 530, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/intent_generation/venv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 236, in run
    super().run()
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 396, in stop
    time.sleep(0.1)
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 530, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2023-10-19 04:48:08 +0000] [408041] [INFO] Starting gunicorn 21.2.0
[2023-10-19 04:48:08 +0000] [408041] [INFO] Listening at: http://0.0.0.0:9000 (408041)
[2023-10-19 04:48:08 +0000] [408041] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-10-19 04:48:08 +0000] [408044] [INFO] Booting worker with pid: 408044
[2023-10-19 04:48:08 +0000] [408045] [INFO] Booting worker with pid: 408045
2023-10-19 04:48:15.807288: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-19 04:48:15.829806: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2023-10-19 04:48:16 +0000] [408041] [INFO] Handling signal: term
[2023-10-19 04:48:16 +0000] [408041] [ERROR] Worker (pid:408045) was sent SIGTERM!
[2023-10-19 04:48:16 +0000] [408041] [ERROR] Worker (pid:408044) was sent SIGTERM!
[2023-10-19 04:48:16 +0000] [408041] [INFO] Shutting down: Master
[2023-10-19 04:49:08 +0000] [408165] [INFO] Starting gunicorn 21.2.0
[2023-10-19 04:49:08 +0000] [408165] [INFO] Listening at: http://0.0.0.0:9000 (408165)
[2023-10-19 04:49:08 +0000] [408165] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-10-19 04:49:08 +0000] [408168] [INFO] Booting worker with pid: 408168
[2023-10-19 04:49:08 +0000] [408169] [INFO] Booting worker with pid: 408169
2023-10-19 04:49:14.237001: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-19 04:49:14.330606: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-19 04:49:15.155453: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-10-19 04:49:15.506664: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-10-19 04:49:15.944325: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-19 04:49:15.948526: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-10-19 04:49:16.338278: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-19 04:49:16.342420: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
[2023-10-19 04:49:21 +0000] [408169] [INFO] Started server process [408169]
[2023-10-19 04:49:21 +0000] [408169] [INFO] Waiting for application startup.
[2023-10-19 04:49:21 +0000] [408169] [INFO] Application startup complete.
[2023-10-19 04:49:21 +0000] [408168] [INFO] Started server process [408168]
[2023-10-19 04:49:21 +0000] [408168] [INFO] Waiting for application startup.
[2023-10-19 04:49:21 +0000] [408168] [INFO] Application startup complete.
[2023-10-19 04:50:00 +0000] [408168] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 230, in jsonable_encoder
    data = dict(obj)
TypeError: 'numpy.float32' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 235, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/fastapi/routing.py", line 291, in app
    content = await serialize_response(
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/fastapi/routing.py", line 179, in serialize_response
    return jsonable_encoder(response_content)
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 209, in jsonable_encoder
    jsonable_encoder(
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 209, in jsonable_encoder
    jsonable_encoder(
  File "/home/ubuntu/intent_generation/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 238, in jsonable_encoder
    raise ValueError(errors) from e
ValueError: [TypeError("'numpy.float32' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
[2023-10-19 04:52:13 +0000] [408165] [INFO] Handling signal: term
[2023-10-19 04:52:13 +0000] [408168] [INFO] Shutting down
[2023-10-19 04:52:13 +0000] [408169] [INFO] Shutting down
[2023-10-19 04:52:13 +0000] [408168] [INFO] Waiting for application shutdown.
[2023-10-19 04:52:13 +0000] [408168] [INFO] Application shutdown complete.
[2023-10-19 04:52:13 +0000] [408168] [INFO] Finished server process [408168]
[2023-10-19 04:52:13 +0000] [408168] [INFO] Worker exiting (pid: 408168)
[2023-10-19 04:52:13 +0000] [408169] [INFO] Waiting for application shutdown.
[2023-10-19 04:52:13 +0000] [408169] [INFO] Application shutdown complete.
[2023-10-19 04:52:13 +0000] [408169] [INFO] Finished server process [408169]
[2023-10-19 04:52:13 +0000] [408169] [INFO] Worker exiting (pid: 408169)
[2023-10-19 04:52:15 +0000] [408165] [INFO] Shutting down: Master
[2023-10-19 04:52:17 +0000] [408333] [INFO] Starting gunicorn 21.2.0
[2023-10-19 04:52:17 +0000] [408333] [INFO] Listening at: http://0.0.0.0:9000 (408333)
[2023-10-19 04:52:17 +0000] [408333] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-10-19 04:52:17 +0000] [408344] [INFO] Booting worker with pid: 408344
[2023-10-19 04:52:17 +0000] [408348] [INFO] Booting worker with pid: 408348
2023-10-19 04:52:35.205341: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-19 04:52:35.205341: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-19 04:52:36.701560: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-10-19 04:52:36.707457: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-10-19 04:52:38.658746: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-19 04:52:38.658746: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-10-19 04:52:38.665808: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-10-19 04:52:38.666165: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
[2023-10-19 04:52:44 +0000] [408344] [INFO] Started server process [408344]
[2023-10-19 04:52:44 +0000] [408344] [INFO] Waiting for application startup.
[2023-10-19 04:52:44 +0000] [408344] [INFO] Application startup complete.
[2023-10-19 04:52:45 +0000] [408348] [INFO] Started server process [408348]
[2023-10-19 04:52:45 +0000] [408348] [INFO] Waiting for application startup.
[2023-10-19 04:52:45 +0000] [408348] [INFO] Application startup complete.
